apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels:
        app: vllm
    spec:
      containers:
        - name: vllm
          image: vllm/vllm-openai:latest
          args:
            - "--model"
            - "{{ .Values.model.name }}"
          ports:
            - containerPort: 8000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
